MasterEdiciones.Libros/ME.Libros.Web/Models/CobradorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

using ME.Libros.Dominio.General;

namespace ME.Libros.Web.Models
{
    public class CobradorViewModel
    {
        #region Constructor(s)

        public CobradorViewModel()
        {
            LocalidadesAsignadas = new List<LocalidadViewModel>();
            LocalidadesNoAsignadas = new List<LocalidadViewModel>();
        }

        public CobradorViewModel(CobradorDominio cobrador)
        {
            Id = cobrador.Id;
            FechaAlta = cobrador.FechaAlta;
            Nombre = cobrador.Nombre;
            Apellido = cobrador.Apellido;
            Dni = cobrador.Dni;
            Localidad = new LocalidadViewModel(cobrador.Localidad);
            PorcentajeComision = cobrador.PorcentajeComision;
            Direccion = cobrador.Direccion;
            TelefonoFijo = cobrador.TelefonoFijo;
            Celular = cobrador.Celular;
            Email = cobrador.Email;
            LocalidadesAsignadas = new List<LocalidadViewModel>(cobrador.Localidades.Select(la => new LocalidadViewModel(la)));
            LocalidadId = cobrador.Localidad.Id;
            ProvinciaId = cobrador.Localidad.Provincia.Id;
        }
        #endregion

        #region Properties

        [Display(Name = "Codigo", ResourceType = typeof(Messages))]
        public long Id { get; set; }

        [Display(Name = "FechaAlta", ResourceType = typeof(Messages))]
        public DateTime FechaAlta { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerido")]
        [StringLength(100, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "StringLength")]
        [RegularExpression(@"^([a-zA-ZñÑáéíóúÁÉÍÓÚ´]+\s)*[a-zA-ZñÑáéíóúÁÉÍÓÚ´]+$", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "OnlyLetters")]
        public string Nombre { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerido")]
        [StringLength(100, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "StringLength")]
        [RegularExpression(@"^([a-zA-ZñÑáéíóúÁÉÍÓÚ´]+\s)*[a-zA-ZñÑáéíóúÁÉÍÓÚ´]+$", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "OnlyLetters")]
        public string Apellido { get; set; }

        [Display(Name = "Direccion", ResourceType = typeof(Messages))]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerida")]
        [StringLength(200, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "StringLength")]
        public string Direccion { get; set; }

        [Display(Name = "Dni", ResourceType = typeof(Messages))]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerido")]
        [Range(1000000, 100000000, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "RangeValue")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public long Dni { get; set; }

        [Display(Name = "TelefonoFijo", ResourceType = typeof(Messages))]
        [StringLength(11, MinimumLength = 11, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "ExactLenght")]
        [RegularExpression(@"\d{2,4}[-. ]\d{6,8}", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "FormatoInvalido")]
        public string TelefonoFijo { get; set; }

        [StringLength(11, MinimumLength = 11, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "ExactLenght")]
        [RegularExpression(@"\d{2,4}[-. ]\d{6,8}", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "FormatoInvalido")]
        public string Celular { get; set; }

        [StringLength(100, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "StringLength")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "FormatoInvalido")]
        public string Email { get; set; }

        [Display(Name = "Localidad", ResourceType = typeof(Messages))]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerida")]
        public long LocalidadId { get; set; }

        [Display(Name = "Provincia", ResourceType = typeof(Messages))]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerida")]
        public long ProvinciaId { get; set; }

        [Display(Name = "PorcentajeComision", ResourceType = typeof(Messages))]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerida")]
        [Range(0, 100, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "RangeValue")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal PorcentajeComision { get; set; }

        public LocalidadViewModel Localidad { get; set; }

        [Display(Name = "LocalidadesAsignadas", ResourceType = typeof(Messages))]
        public List<LocalidadViewModel> LocalidadesAsignadas { get; set; }

        public List<LocalidadViewModel> LocalidadesNoAsignadas { get; set; }

        public SelectList Provincias { get; set; }

        public SelectList Localidades { get; set; }

        #endregion
    }
}

MasterEdiciones.Libros/ME.Libros.Web/Controllers/CobradorController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

using ME.Libros.Dominio.General;
using ME.Libros.EF;
using ME.Libros.Repositorios;
using ME.Libros.Servicios.General;
using ME.Libros.Utils.Enums;
using ME.Libros.Web.Extensions;
using ME.Libros.Web.Models;

namespace ME.Libros.Web.Controllers
{
    public class CobradorController : BaseController<CobradorDominio>
    {
        public CobradorService CobradorService { get; set; }
        public LocalidadService LocalidadService { get; set; }
        public ProvinciaService ProvinciaService { get; set; }
        public VentaService VentaService { get; set; }

        public CobradorController()
        {
            var modelContainer = new ModelContainer();
            CobradorService = new CobradorService(new EntidadRepository<CobradorDominio>(modelContainer));
            LocalidadService = new LocalidadService(new EntidadRepository<LocalidadDominio>(modelContainer));
            ProvinciaService = new ProvinciaService(new EntidadRepository<ProvinciaDominio>(modelContainer));
            VentaService = new VentaService(new EntidadRepository<VentaDominio>(modelContainer));
        }

        //
        // GET: /Cobrador/
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Id = TempData["Id"];
            ViewBag.Mensaje = TempData["Mensaje"];

            var cobradores = new List<CobradorViewModel>();
            using (CobradorService)
            {
                cobradores.AddRange(CobradorService.Listar()
                    .OrderBy(c => c.Apellido)
                    .ThenBy(c => c.Nombre)
                    .ToList()
                    .Select(c => new CobradorViewModel(c)));
            }

            return View(cobradores);
        }

        [HttpGet]
        public ActionResult Crear()
        {
            var cobradorViewModel = new CobradorViewModel();
            PrepareModel(cobradorViewModel);

            return View(cobradorViewModel);
        }

        [HttpPost]
        public ActionResult Crear(CobradorViewModel cobradorViewModel)
        {
            long resultado = 0;
            var localidadIds = new List<string>();
            if (!string.IsNullOrEmpty(Request.Form["localidadesAsignadas_dualList"]))
            {
                localidadIds = Request.Form["localidadesAsignadas_dualList"].Split(',').ToList();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (CobradorService)
                    {
                        var cobradorDominio = new CobradorDominio
                        {
                            FechaAlta = DateTime.Now,
                            Nombre = cobradorViewModel.Nombre,
                            Apellido = cobradorViewModel.Apellido,
                            Dni = cobradorViewModel.Dni,
                            PorcentajeComision = cobradorViewModel.PorcentajeComision,
                            Direccion = cobradorViewModel.Direccion,
                            TelefonoFijo = cobradorViewModel.TelefonoFijo,
                            Celular = cobradorViewModel.Celular,
                            Email = cobradorViewModel.Email,
                            Localidad = LocalidadService.GetPorId(cobradorViewModel.LocalidadId),
                            Localidades = new List<LocalidadDominio>(),
                        };

                        foreach (var localidadId in localidadIds)
                        {
                            cobradorDominio.Localidades.Add(LocalidadService.GetPorId((Convert.ToInt64(localidadId))));
                        }

                        resultado = CobradorService.Guardar(cobradorDominio);

                        if (resultado <= 0)
                        {
                            foreach (var error in CobradorService.ModelError)
                            {
                                ModelState.AddModelError(error.Key, error.Value);
                            }
                        }
                        else
                        {
                            TempData["Id"] = cobradorDominio.Id;
                            TempData["Mensaje"] = string.Format(Messages.EntidadNueva, Messages.ElCobrador, cobradorDominio.Id);
                        }
                    }
                }
                catch (DbUpdateException ex)
                {
                    var sqlException = ex.GetBaseException() as SqlException;
                    if (sqlException != null && sqlException.Number == 2601)
                    {
                        ModelState.AddModelError("Error",
                            string.Format(ErrorMessages.DniRepetido, cobradorViewModel.Dni, Messages.Cobrador ));
                    }
                    else
                    {
                        ModelState.AddModelError("Error", ErrorMessages.ErrorSistema);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Error", ErrorMessages.ErrorSistema);
                }
            }

            if (resultado == 0)
            {
                PrepareModel(cobradorViewModel, localidadIds);
            }

            return resultado > 0
                ? (ActionResult)RedirectToAction("Index")
                : View(cobradorViewModel);
        }

        [HttpGet]
        public ActionResult Modificar(int id)
        {
            CobradorViewModel cobradorViewModel;
            using (CobradorService)
            {
                cobradorViewModel = new CobradorViewModel(CobradorService.GetPorId(id));
            }
            PrepareModel(cobradorViewModel);

            return View(cobradorViewModel);
        }

        [HttpPost]
        public ActionResult Modificar(CobradorViewModel cobradorViewModel)
        {
            var localidadIds = new List<string>();
            if (!string.IsNullOrEmpty(Request.Form["localidadesAsignadas_dualList"]))
            {
                localidadIds = Request.Form["localidadesAsignadas_dualList"].Split(',').ToList();
            }

            if (!ModelState.IsValid)
            {
                PrepareModel(cobradorViewModel, localidadIds);
                return View(cobradorViewModel);
            }

            var nombreLocalidades = string.Empty;
            long resultado = 0;
            try
            {
                var cobradorDominio = CobradorService.GetPorId(cobradorViewModel.Id);
                var i = 0;
                foreach (var localidadAsignada in cobradorDominio.Localidades)
                {
                    if (!localidadIds.Contains(localidadAsignada.Id.ToString()))
                    {
                        if (VentaService.ListarAsQueryable().Any(v => (v.Cliente.Localidad.Id == localidadAsignada.Id
                                                                       && v.Cobrador.Id == cobradorDominio.Id
                                                                       && v.Estado == EstadoVenta.Vigente)))
                        {
                            nombreLocalidades += ", " + localidadAsignada.Nombre;
                            i++;
                        }
                    }
                }

                if (i > 0)
                {
                    nombreLocalidades = nombreLocalidades.Substring(2, nombreLocalidades.Length - 2);

                    if (i == 1)
                    {
                        ModelState.AddModelError("localidad",
                            "La localidad: " + nombreLocalidades +
                            " debe estar asignada ya que existen ventas asociadas al cobrador que intenta modificar");
                    }
                    else if (i > 1)
                    {
                        ModelState.AddModelError("localidades",
                            "Las localidades: " + nombreLocalidades +
                            " deben estar asignadas ya que existen ventas asociadas al cobrador que intenta modificar");
                    }
                }
                else
                {
                    using (CobradorService)
                    {
                        cobradorDominio.Nombre = cobradorViewModel.Nombre;
                        cobradorDominio.Apellido = cobradorViewModel.Apellido;
                        cobradorDominio.Dni = cobradorViewModel.Dni;
                        cobradorDominio.PorcentajeComision = cobradorViewModel.PorcentajeComision;
                        cobradorDominio.Direccion = cobradorViewModel.Direccion;
                        cobradorDominio.TelefonoFijo = cobradorViewModel.TelefonoFijo;
                        cobradorDominio.Celular = cobradorViewModel.Celular;
                        cobradorDominio.Email = cobradorViewModel.Email;
                        cobradorDominio.Localidad = LocalidadService.GetPorId(cobradorViewModel.LocalidadId);
                        cobradorDominio.Localidades.Clear();

                        foreach (var localidad in localidadIds)
                        {
                            cobradorDominio.Localidades.Add(LocalidadService.GetPorId((Convert.ToInt64(localidad))));
                        }

                        resultado = CobradorService.Guardar(cobradorDominio);
                        if (resultado <= 0)
                        {
                            foreach (var error in CobradorService.ModelError)
                            {
                                ModelState.AddModelError(error.Key, error.Value);
                            }
                        }
                        else
                        {
                            TempData["Id"] = cobradorViewModel.Id;

MasterEdiciones.Libros/ME.Libros.Web/Views/Cobrador/Crear.cshtml
@model ME.Libros.Web.Models.CobradorViewModel

<h3 class="page-header">Nuevo cobrador</h3>
@using (Html.BeginForm("Crear", "Cobrador", FormMethod.Post, new { id = "formCobrador", @class = "form-horizontal formEntidad" }))
{
    @Html.Partial("Shared/Form_Partial", Model)

    <div class="row">
        <div class="col-md-10">
            <div class="text-right">
                <a id="btnCancelar" class="btn btn-default" href="@Url.Action("Index")" title="Cancelar">
                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                    Cancelar
                </a>
                <button type="submit" class="btn btn-success" title="Crear cobrador">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    Crear
                </button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        if ($("#Dni").val() == "0") {
            $("#Dni").val("");
        }
    });
</script>

MasterEdiciones.Libros/ME.Libros.Web/Views/Cobrador/Eliminar.cshtml
@using ME.Libros.Web.Models
<!-- Modal -->
<div class="modal fade modalEliminar" id="modalEliminarCobrador" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar cobrador</h4>
            </div>
            <div class="modal-body">
                ¿Esta seguro que desea eliminar @(Model is CobradorViewModel ? "este cobrador" : "el cobrador seleccionado")?
            </div>
            <div class="modal-footer">
                <div class="row text-left">
                    <div class="col-md-12">
                        <div class="alert alert-danger validationSummary hide" role="alert">
                            <a class="close" data-hide="alert" aria-hidden="true">×</a>
                            <b>Mensajes:</b>
                        </div>
                    </div>
                </div>
                <button type="button" class="btn btn-default btnCancelarEliminar" data-dismiss="modal">Cancelar</button>
                <button id="btnAceptar" type="button" class="btn btn-primary">Aceptar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#btnAceptar").on("click", function () {
        var id = $("#idEntidad").val();
        var success = ('@Messages.EntidadEliminada').replace("{0}", '@Messages.ElCobrador').replace("{1}", id);
        eliminarEntidad("@Url.Action("Eliminar")", success, '@ErrorMessages.ErrorEliminar');
    });
</script>

MasterEdiciones.Libros/ME.Libros.Web/Views/Cobrador/Index.cshtml
@model IEnumerable<ME.Libros.Web.Models.CobradorViewModel>

<h3 class="page-header">Cobradores</h3>
<a class="btn btn-success btnNuevo" href="@Url.Action("Crear")" role="button">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Nuevo
</a>

<table class="dataTableCustom">
    <thead>
        <tr>
            <th class="columnaCodigo no-sort">@Html.DisplayNameFor(model => model.Id)</th>
            <th>@Html.DisplayNameFor(model => model.Nombre)</th>
            <th>@Html.DisplayNameFor(model => model.Apellido)</th>
            <th>@Html.DisplayNameFor(model => model.Dni)</th>
            <th>@Html.DisplayNameFor(model => model.Localidad)</th>
            <th>@Html.DisplayNameFor(model => model.LocalidadesAsignadas)</th>
            <th class="columnaAcciones">Acciones</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr id=@("tr_"+ item.Id)>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
            <td>@Html.DisplayFor(modelItem => item.Apellido)</td>
            <td>@Html.DisplayFor(modelItem => item.Dni)</td>
            <td>@Html.DisplayFor(modelItem => item.Localidad.Nombre), @Html.DisplayFor(modelItem => item.Localidad.Provincia.Nombre)</td>
            <td>@string.Join(" | ", item.LocalidadesAsignadas.Select(la => la.Nombre))</td>
            <td>
                <a class="btn btn-warning btn-sm btnModificar" type="button" href="@Url.Action("Modificar", new { id = item.Id})" title="Modificar cobrador">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <button class="btn btn-danger btn-sm" type="button" data-toggle="modal" data-target="#modalEliminarCobrador" onclick="javascript:setearId(@item.Id);" title="Eliminar cobrador">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </button>
            </td>
        </tr>
    }
</table>

@Html.Partial("Eliminar")
<input type="hidden" id="idEntidad" />

MasterEdiciones.Libros/ME.Libros.Web/Views/Cobrador/Modificar.cshtml
@model ME.Libros.Web.Models.CobradorViewModel

<h3 class="page-header">Modificar cobrador</h3>
@using (Html.BeginForm("Modificar", "Cobrador", FormMethod.Post, new { id = "formCobrador", @class = "form-horizontal formEntidad" }))
{
    @Html.Partial("Shared/Form_Partial", Model)
    @Html.HiddenFor(model => model.Id)

    <div class="row">
        <div class="col-md-10">
            <div class="text-right">
                <button class="btn btn-danger" type="button" data-toggle="modal" data-target="#modalEliminarCobrador" title="Eliminar cobrador">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    Eliminar
                </button>
                <a class="btn btn-default btnCancelar" href="@Url.Action("Index")" title="Cancelar">
                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                    Cancelar
                </a>
                <button type="submit" class="btn btn-warning" title="Modificar cobrador">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    Modificar
                </button>
            </div>
        </div>
    </div>
}

<input type="hidden" id="idEntidad" value="@Model.Id" />
@Html.Partial("Eliminar")