MasterEdiciones.Libros/ME.Libros.Web/Models/ZonaViewModel.cs
using System.ComponentModel.DataAnnotations;
using ME.Libros.Dominio.General;

namespace ME.Libros.Web.Models
{
    public class ZonaViewModel
    {
        #region Constructor(s)

        public ZonaViewModel()
        {
        }

        public ZonaViewModel(ZonaDominio zona)
        {
            Id = zona.Id;
            Nombre = zona.Nombre;
            Descripcion = zona.Descripcion;
        }

        #endregion

        #region Properties

        [Display(Name = "Codigo", ResourceType = typeof(Messages))]
        public long Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Requerido")]
        [StringLength(80, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "StringLength")]
        [RegularExpression(@"^([a-zA-ZñÑáéíóúÁÉÍÓÚ´0-9]+\s)*[a-zA-ZñÑáéíóúÁÉÍÓÚ´0-9]+$", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "OnlyLettersAndNumbers")]
        public string Nombre { get; set; }

        [StringLength(250, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "StringLength")]
        public string Descripcion { get; set; }

        #endregion
    }
}

MasterEdiciones.Libros/ME.Libros.Web/Controllers/ZonaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

using ME.Libros.Dominio.General;
using ME.Libros.EF;
using ME.Libros.Repositorios;
using ME.Libros.Servicios.General;
using ME.Libros.Web.Extensions;
using ME.Libros.Web.Models;

namespace ME.Libros.Web.Controllers
{
    public class ZonaController : BaseController<ZonaDominio>
    {
        //
        // GET: /Zona/
        public ZonaService ZonaService { get; set; }
        public ActionResult Index()
        {
            ViewBag.Id = TempData["Id"];
            ViewBag.Mensaje = TempData["Mensaje"];

            var zonas = new List<ZonaViewModel>();
            using (ZonaService)
            {
                zonas.AddRange(ZonaService.Listar()
                    .ToList()
                    .Select(z => new ZonaViewModel(z))
                    .Where(z => z.Id != 1));
            }

            return View(zonas);
        }

        public ZonaController()
        {
            var modelContainer = new ModelContainer();
            ZonaService = new ZonaService(new EntidadRepository<ZonaDominio>(modelContainer));
        }

        [HttpGet]
        public ActionResult Crear()
        {
            var zonaViewModel = new ZonaViewModel();

            return View(zonaViewModel);
        }

        [HttpPost]
        public ActionResult Crear(ZonaViewModel zonaViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(zonaViewModel);
            }

            long resultado = 0;
            try
            {
                using (ZonaService)
                {
                    var zonaDominio = new ZonaDominio
                    {
                        FechaAlta = DateTime.Now,
                        Nombre = zonaViewModel.Nombre,
                        Descripcion = zonaViewModel.Descripcion,
                    };

                    resultado = ZonaService.Guardar(zonaDominio);
                    if (resultado <= 0)
                    {
                        foreach (var error in ZonaService.ModelError)
                        {
                            ModelState.AddModelError(error.Key, error.Value);
                        }
                    }
                    else
                    {
                        TempData["Id"] = zonaDominio.Id;
                        TempData["Mensaje"] = string.Format(Messages.EntidadNueva, Messages.LaZona, zonaDominio.Id);
                    }
                }
            }
            catch (Exception ex)
            {
                // Log
                ModelState.AddModelError("Error", ErrorMessages.ErrorSistema);
            }

            return resultado > 0
                    ? (ActionResult)RedirectToAction("Index")
                    : View(zonaViewModel);
        }

        [HttpGet]
        public JsonResult Eliminar(int id, string redirectUrl)
        {
            var isRedirect = !string.IsNullOrEmpty(redirectUrl);
            try
            {
                using (ZonaService)
                {
                    var zonaDominio = ZonaService.GetPorId(id);
                    ZonaService.Eliminar(zonaDominio);

                    if (isRedirect)
                    {
                        TempData["Id"] = zonaDominio.Id;
                        TempData["Mensaje"] = string.Format(Messages.EntidadEliminada, Messages.LaZona, zonaDominio.Id);
                    }
                }
            }
            catch (DbUpdateException ex)
            {
                var sqlException = ex.GetBaseException() as SqlException;

                if (sqlException != null && sqlException.Number == 547)
                {
                    ModelState.AddModelError("Error", string.Format(ErrorMessages.DatosAsociados, Messages.LaZona));
                }
                else
                {
                    ModelState.AddModelError("Error", ErrorMessages.ErrorSistema);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ErrorMessages.ErrorSistema);
            }

            return new JsonResult
            {
                Data = new
                {
                    Success = ModelState.IsValid,
                    Errors = ModelState.GetErrors(),
                    isRedirect,
                    redirectUrl
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [HttpGet]
        public ActionResult Modificar(int id)
        {
            ZonaViewModel zonaViewModel;
            using (ZonaService)
            {
                var zonaDominio = ZonaService.GetPorId(id);
                zonaViewModel = new ZonaViewModel(zonaDominio);
            }

            return View(zonaViewModel);
        }

        [HttpPost]
        public ActionResult Modificar(ZonaViewModel zonaViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(zonaViewModel);
            }

            long resultado = 0;
            try
            {
                using (ZonaService)
                {
                    var zonaDominio = ZonaService.GetPorId(zonaViewModel.Id);
                    zonaDominio.Nombre = zonaViewModel.Nombre;
                    zonaDominio.Descripcion = zonaViewModel.Descripcion;

                    resultado = ZonaService.Guardar(zonaDominio);
                    if (resultado <= 0)
                    {
                        foreach (var error in ZonaService.ModelError)
                        {
                            ModelState.AddModelError(error.Key, error.Value);
                        }
                    }
                    else
                    {
                        TempData["Id"] = zonaDominio.Id;
                        TempData["Mensaje"] = string.Format(Messages.EntidadModificada, Messages.LaZona, zonaDominio.Id);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ErrorMessages.ErrorSistema);
            }

            return resultado > 0
                    ? (ActionResult)RedirectToAction("Index")
                    : View(zonaViewModel);
        }
    }
}

MasterEdiciones.Libros/ME.Libros.Web/Views/Zona/Crear.cshtml
@model ME.Libros.Web.Models.ZonaViewModel

<h3 class="page-header">Nueva zona</h3>
@using (Html.BeginForm("Crear", "Zona", FormMethod.Post, new { id = "formZona", @class = "form-horizontal formEntidad" }))
{
    @Html.Partial("Shared/Form_Partial", Model)

    <div class="row">
        <div class="col-md-10">
            <div class="alert alert-danger validationSummary @(ViewData.ModelState.IsValid ? "hide" : "")" role="alert">
                <a class="close" data-hide="alert" aria-hidden="true">×</a>
                <b>Mensajes:</b>
                @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationSummary().ToString()))
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <div class="text-right">
                <a id="btnCancelar" class="btn btn-default" href="@Url.Action("Index")">
                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                    Cancelar
                </a>
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    Crear
                </button>
            </div>
        </div>
    </div>
}

MasterEdiciones.Libros/ME.Libros.Web/Views/Zona/Eliminar.cshtml
@using ME.Libros.Web.Models


<!-- Modal -->
<div class="modal fade modalEliminar" id="modalEliminarZona" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar zona</h4>
            </div>
            <div class="modal-body">
                ¿Esta seguro que desea eliminar @(Model is ZonaViewModel ? "esta zona" : "la zona seleccionada")?
            </div>
            <div class="modal-footer">
                <div class="row text-left">
                    <div class="col-md-12">
                        <div class="alert alert-danger validationSummary hide" role="alert">
                            <a class="close" data-hide="alert" aria-hidden="true">×</a>
                            <b>Mensajes:</b>
                        </div>
                    </div>
                </div>
                <button type="button" class="btn btn-default btnCancelarEliminar" data-dismiss="modal">Cancelar</button>
                <button id="btnAceptar" type="button" class="btn btn-primary">Aceptar</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

        $("#btnAceptar").on("click", function () {
            var id = $("#idEntidad").val();
            var success = ('@Messages.EntidadEliminada').replace("{0}", '@Messages.LaZona').replace("{1}", id);
            eliminarEntidad("@Url.Action("Eliminar")", success, '@ErrorMessages.ErrorEliminar');
        });

</script>

MasterEdiciones.Libros/ME.Libros.Web/Views/Zona/Index.cshtml
@model IEnumerable<ME.Libros.Web.Models.ZonaViewModel>

<h3 class="page-header">Zonas</h3>
<a class="btn btn-success btnNuevo" href="@Url.Action("Crear")" role="button">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Nuevo
</a>

<table class="dataTableCustom">
    <thead>
        <tr>
            <th class="columnaCodigo no-sort">@Html.DisplayNameFor(model => model.Id)</th>
            <th>@Html.DisplayNameFor(model => model.Nombre)</th>
            <th>@Html.DisplayNameFor(model => model.Descripcion)</th>
            <th class="columnaAcciones">Acciones</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr id=@("tr_"+ item.Id)>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
            <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
            <td>
                <a class="btn btn-warning btn-sm btnModificar" type="button" href="@Url.Action("Modificar", new { id = item.Id})" title="Modificar zona">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <button class="btn btn-danger btn-sm btnEliminar" type="button" data-toggle="modal" data-target="#modalEliminarZona" onclick="javascript:setearId(@item.Id);" title="Eliminar zona">
                    <span class=" glyphicon glyphicon-trash" aria-hidden="true">
                    </span>
                </button>
            </td>
        </tr>
    }
</table>
@Html.Partial("Eliminar")
<input type="hidden" id="idEntidad" />

MasterEdiciones.Libros/ME.Libros.Web/Views/Zona/Modificar.cshtml
@model ME.Libros.Web.Models.ZonaViewModel

<h3 class="page-header">Modificar zona</h3>
@using (Html.BeginForm("Modificar", "Zona", FormMethod.Post, new { id = "formZona", @class = "form-horizontal formEntidad" }))
{
    @Html.Partial("Shared/Form_Partial", Model)
    @Html.HiddenFor(model => model.Id)

    <div class="row">
        <div class="col-md-10">
            <div class="text-right">
                <button class="btn btn-danger" type="button" data-toggle="modal" data-target="#modalEliminarZona" title="Eliminar zona">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    Eliminar
                </button>
                <a class="btn btn-default btnCancelar" href="@Url.Action("Index")" title="Cancelar">
                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                    Cancelar
                </a>
                <button type="submit" class="btn btn-warning" title="Modificar zona">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    Modificar
                </button>
            </div>
        </div>
    </div>

}

@Html.Partial("Eliminar")
<input type="hidden" id="idEntidad" value="@Model.Id" />